name: Verify Release
# This verifies that a given PR has the required labels before merge into the default branch.
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  merge_group:
    types: [checks_requested]

jobs:
  verify-that-semver-label-is-present:
    name: Verify Release
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 10
    if: ${{ always() && github.event_name != 'merge_group' }}
    steps:
      - name: Verify PR labels
        uses: docker://agilepathway/pull-request-label-checker:latest@sha256:14f5f3dfda922496d07d53494e2d2b42885165f90677a1c03d600059b7706a61
        with:
          one_of: major,minor,patch,internal
          repo_token: ${{ secrets.GITHUB_TOKEN }}
